---
- name: ansible module
  hosts: servers
  become: false
  tasks:
    - name: copy jar file to remote server
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/test_pipeline/target/sample.jar
        dest:
        owner:
        mode: "0644"
