---
- name: ansible module
  hosts: servers
  become: false
  tasks:
    - name: copy jar file to remote server
      ansible.builtin.copy:
        src: ./ansible.yml
        dest: /home/hossain/Desktop
        owner: hossain
        mode: "0644"
